version: "3.6"
services:
  postgres:
    ports:
      - "5556:5432"
    image: postgres
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
  graphql-engine:
    image: hasura/graphql-engine:v1.3.3
    ports:
      - "8686:8686"
    depends_on:
      - "postgres"
    restart: always
    environment:
      HASURA_GRAPHQL_AUTH_HOOK: https://pacific-coast-90135.herokuapp.com/webhook
      HASURA_GRAPHQL_SERVER_PORT: 8686
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
      HASURA_GRAPHQL_DISABLE_CORS: "false"
      HASURA_GRAPHQL_AUTH_HOOK_MODE: GET
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
volumes:
  db_data:
